import os

PROMETHEUS_URL = "http://localhost:9090"
NODE_EXPORTER_URL = "http://localhost:9100"
CPU_THRESHOLD = 30
MEMORY_THRESHOLD = 25
DISK_THRESHOLD = 60
NETWORK_THRESHOLD = 70

SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL", "")
EMAIL_SMTP_SERVER = os.getenv("EMAIL_SMTP_SERVER", "")
EMAIL_USERNAME = os.getenv("EMAIL_USERNAME", "")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD", "")
