import os

PROMETHEUS_URL = "http://localhost:9090"
NODE_EXPORTER_URL = "http://localhost:9100"
CPU_THRESHOLD = 70
MEMORY_THRESHOLD = 20
DISK_THRESHOLD = 60
NETWORK_THRESHOLD = 70

SPIKE_DURATION_SECONDS = 120
MONITORING_INTERVAL_SECONDS = 60

SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL", "")
EMAIL_SMTP_SERVER = os.getenv("EMAIL_SMTP_SERVER", "")
EMAIL_USERNAME = os.getenv("EMAIL_USERNAME", "")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD", "")
